import { vi } from "vitest";

vi.mock("@/lib/db", () => ({
  db: {
    user: { findUnique: vi.fn(), create: vi.fn(), upsert: vi.fn(), update: vi.fn() },
    organization: { findUnique: vi.fn(), findFirst: vi.fn(), create: vi.fn() },
    organizationMember: { findUnique: vi.fn(), findFirst: vi.fn(), create: vi.fn() },
    service: { findFirst: vi.fn(), findMany: vi.fn(), create: vi.fn(), update: vi.fn() },
    staff: { findFirst: vi.fn(), findMany: vi.fn(), create: vi.fn(), count: vi.fn() },
    staffService: { findUnique: vi.fn() },
    availabilityRule: { findUnique: vi.fn(), findMany: vi.fn() },
    appointment: {
      findFirst: vi.fn(),
      findMany: vi.fn(),
      create: vi.fn(),
      count: vi.fn(),
      groupBy: vi.fn(),
    },
    reminder: { create: vi.fn(), findMany: vi.fn(), update: vi.fn() },
    subscription: { findUnique: vi.fn() },
    auditLog: { create: vi.fn() },
    customer: { findFirst: vi.fn(), create: vi.fn(), findMany: vi.fn() },
    businessClosedDay: { findUnique: vi.fn(), findMany: vi.fn(), create: vi.fn(), deleteMany: vi.fn() },
    consentLog: { create: vi.fn() },
    dataDeletionRequest: { create: vi.fn() },
    invoiceProfile: { findUnique: vi.fn(), create: vi.fn(), upsert: vi.fn() },
    whatsAppAutoReplySettings: {
      findUnique: vi.fn(),
      findFirst: vi.fn(),
      upsert: vi.fn(),
      update: vi.fn(),
      create: vi.fn(),
    },
    whatsAppInboundMessage: {
      findUnique: vi.fn(),
      findFirst: vi.fn(),
      create: vi.fn(),
      findMany: vi.fn(),
      count: vi.fn(),
    },
    whatsAppAutoReplyLog: {
      create: vi.fn(),
      findMany: vi.fn(),
      count: vi.fn(),
      update: vi.fn(),
    },
    whatsAppContactPreference: {
      findUnique: vi.fn(),
      findFirst: vi.fn(),
      upsert: vi.fn(),
      update: vi.fn(),
      create: vi.fn(),
    },
    passwordResetToken: {
      create: vi.fn(),
      findUnique: vi.fn(),
      update: vi.fn(),
      deleteMany: vi.fn(),
    },
    $transaction: vi.fn(),
  },
}));
